USE caoTrilha2;

DROP TABLE IF EXISTS users;


CREATE TABLE users (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    is_admin BOOLEAN NOT NULL DEFAULT 0,
    nome VARCHAR(100) NOT NULL,
    telefone VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    morada VARCHAR(150) NOT NULL,
    password VARCHAR(255) NOT NULL
);

